### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by 4silvertooth** [sebbekarlsson/plicit#1]
https://github.com/sebbekarlsson/plicit/blob/e3e187127da299d51a535661cca4e9b1921a66e6/README.md?plain=1#L66

Should be `component will begin rendering`

**Comment by sebbekarlsson** [comment]
@4silvertooth  Good catch! Thank you, I'll fix it when I have some time :+1:

**Comment by sebbekarlsson** [comment]
Solved :1st_place_medal:
